theme: jekyll-theme-cayman

# Name of your site (displayed in the header)
title: What will AI mean for Africa?

# Short bio or description (displayed in the header)
description: An event hosted by the Effective Altruism society at the University of Cape Town.
